server:
  port: 8001

spring:
  application:
    name: gateway-service
  zipkin:
#    base-url: http://39.105.91.69:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true
  rabbitmq:
    host: 39.105.91.69
    username: admin
    password: 123456
    port: 5672
    listener:
       direct:
        retry:
          enabled: true
       simple:
        retry:
          enabled: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/



management:
  server:
    port: 9003
  endpoint:
    health:
      show-details: always
      #boot2.0 请求发生变化http://localhost:9001/actuator/XX
      #boot2.0 Actuator只暴露health和info
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true






zuul:
  routes:
    order-service:
      path: /api/order/**
      service-id: order-service
    user-service:
      path: /api/user-service/**
      service-id: user-service




