server:
  port: 8081
  servlet:
    context-path: /api/demo/

#    server.tomcat.remote_ip_header=x-forwarded-for
#    server.tomcat.protocol_header=x-forwarded-proto
#    server.tomcat.port-header=X-Forwarded-Port
#    server.use-forward-headers=true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://39.105.91.69:3306/dc_user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.105.91.69
    port: 6379
    jedis:
      pool:
        max-active: 8



logging:
    level:
      com.dc.demo.mapper: debug
#    file: my.log
#    path: E:/logs
