server:
  port: 8762


management:
  server:
    port: 9002
    #开起监控详情
  endpoint:
    health:
      show-details: always
      #boot2.0 请求发生变化http://localhost:9001/actuator/XX
      #boot2.0 Actuator只暴露health和info
    web:
      exposure:
        include: "*"


eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/




